### ISSUE TITLE
TypeError when building

### ISSUE THREAD

**Issue by Heath123** [sentialx/electron-global#26]
```
TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received type number (9)
    at Object.writeFile (internal/fs/promises.js:542:5)
    at Object.<anonymous> (/home/heath/SyncedProjects/pakkit/node_modules/electron-global/build/index.js:91:29)
    at Generator.next (<anonymous>)
    at fulfilled (/home/heath/SyncedProjects/pakkit/node_modules/electron-global/build/index.js:4:58) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

**Comment by sentialx** [comment]
I'm no longer working on this project.
